### ISSUE TITLE
Missing /etc/tmpfiles.d/ceph.conf in ceph-common

### ISSUE THREAD

**Issue by jehane** [CentOS-Storage-SIG/ceph#1]
Ceph use directory in /var/run/ceph to work but on centos 7, /var/run is a tmpfs and not persistant. 
A /etc/tmpfiles/ceph.conf is allowing the creation of the layout at every reboot but it's missing in CentOS rpm 
see https://github.com/ceph/ceph/pull/4317/files 
and http://tracker.ceph.com/issues/15553

**Comment by fcami** [comment]
Hi Jehane, Thanks for reporting - we currently ship unmodified RPMs from upstream. Are you seeing this on Hammer or Jewel?

**Comment by jehane** [comment]
We are using hammer (Ceph hammer + RDO mikata)

**Comment by apevec** [comment]
This is fixed in Jewel and as fcami mentioned, Storage SIG is rebuilding upstream SRPMs as-is.
Hammer is EOL and OpenStack Mitaka will be soon[1] so best would be migrate to Ceph Jewel + RDO Newton.

[1] https://releases.openstack.org/
