### ISSUE TITLE
ppc64le releases

### ISSUE THREAD

**Issue by hamzy** [CentOS-Storage-SIG/ceph#9]
What is the process to build ppc64le versions of the packages in ceph-luminious or ceph-jewel?

**Comment by nixpanic** [comment]
Ceph luminious is available for ppc64le. You should be able to install it just like x86_64:

```
# yum install centos-release-ceph-luminious
# yum install ceph
```

If this does not work, please report the issue on the [CentOS devel mailinglist](https://lists.centos.org/mailman/listinfo/centos-devel). I think GitHub issues are not really monitored (as you may guess from the lacking response).
